OPRID = {'ACD':	'Accordion',
         'AB': 'Air Bubbles',
         'AO': 'Anneal Off',
         'ASL': 'Anneal Segment Length',
         'BC': 'Bad Cut',
         'ВP': 'Lump/Bump',
         'BW': 'Broken Wire',
         'CRK': 'Cracks',
         'DF': 'Overmelt',
         'DH': 'Damaged Hypotube',
         'DIS':	'Damaged Inner Surface',
         'DL': 'Damaged Liner',
         'DS': 'Damaged Shaft',
         'DSU': 'Damaged Surface',
         'DT': 'Damaged Tip',
         'DW': 'Damaged Wire',
         'DEL':	'Delamination',
         '#1US': 'Dim 1 Outer Diameter Oversized',
         '#1OS':	'Dim 1 Outer Diameter Undersized',
         '#2OS':	'Dim 2 Inner Diameter Oversized',
         '#2US': 'Dim 2 Inner Diameter Undersized',
         '#5OS': 'Dim 5 Length Oversized',
         '#5US':	'Dim 5 Length Undersized',
         '#6OS':	'Dim 6 Outer Diameter Oversized',
         '#6US': 'Dim 6 Outer Diameter Undersized',
         '#7OS':	'Dim 7 Length Oversized',
         '#7US':	'Dim 7 Length Undersized',
         '#9OS': 'Dim 9 Outer Diameter Oversized',
         '#9US':	'Dim 9 Outer Diameter Undersized',
         'DISC':	'Discoloration',
         'DST': 'Distortion',
         'DU': 'Dropped Unit',
         'EXG':	'Exit Gate Off',
         'EH': 'Exposed Hypotube',
         'EW': 'Exposed Wire',
         'LT': 'Failed Leak Test',
         'FL': 'Flash',
         'FM': 'Foreign Material',
         'FB': 'Fibers',
         'GAP':	'Gap',
         'GD': 'Glue Damage',
         'HOS': 'Heat Off Stopper',
         'TEMP':	'Incorrect Tempeature',
         'IDB': 'Inner Diameter Block',
         'IDBO':	'Inner Diameter Blow Out',
         'LT': 'Leak Test',
         'LS': 'Length Short',
         'LPM': 'Loose Particulate Matter',
         'MOF':	'Material Overflow',
         'MP':	'Micropores',
         'MA': 'Misaligned',
         'MAS':	'Misassembled',
         'MEX': 'Misassembled Extrusions',
         'OF': 'Over Flow',
         'OA': 'Overalign',
         'OAL OS': 'Overall Length Long',
         'OAL US':	'Overall Length Short',
         'OF': 'Overflow',
         'PBC' 'Proximal Bad Cut'
         'PC': 'Pancake',
         'PROT': 'Protrusion',
         'GN11': 'PTFE on Pull Wire',
         'RM': 'Raised Material',
         'RG': 'Reglue',
         'SP': 'Samples',
         'SCR':	'Scratches',
         'SLOS': 'Segment Length Long',
         'SLUS': 'Segment Length Short',
         'SW': 'Short Wire',
         'SKV': 'Skive Mark',
         'SKVD': 'Skive Damage',
         'STN': 'Stain',
         'STR': 'Stringers',
         'TT': 'Tensile Test',
         'TL': 'Tails',
         'TL': 'Tight Liner',
         'TD': 'Tip Damaged',
         'VD': 'Voids',
         'WL': 'White Line',
         'WS':	'White Spot Over Stretch',
         'WC': 'Window Close (SL/US)',
         'WM':	'Window Miscut',
         'OW':	'Window Open (SL/OS)',
         'WB':	'Wire Bent',
         'WO':	'Wire Out',
         'WK': 'Wrinkles'}
COLUMNHEADING = ['Work Center',
                 'Operation',
                 'Scrap Code',
                 'Scrap Description',
                 'Op. Good Qty',
                 'Op. Scrap Qty',
                 'UoM',
                 'PPM____________',
                 'Posting date',
                 'Entry Date',
                 'Prod Order',
                 'Material Number',
                 'Material Description',
                 'Parent Good qty',
                 'Parent Scrap qty',
                 'Order Unit',
                 'Order Type',
                 'Plant',
                 'Entered Good Qty',
                 'Entered Scrap Qty',
                 'Entered UoM']

SCRAP_CODE_MAPPING = {'40D material at wrong length': '1000',
                      'Accordion': '1120',
                      'Air Bubble': '1005',
                      'Air Bubbles': '1005',
                      'Anneal Off': '1008',
                      'Anneal Segment Length': '1008',
                      'Annealing Defect': '1288',
                      'Assembly Movement': '1289',
                      'Bad Cut': '1013',
                      'Bad Cut (Prox Cut ONLY)': '1008',
                      'Bad Print': '1531',
                      'Bad Skive': '1016',
                      'Bent Wire': '1060',
                      'Blocked': '1038',
                      'Bond Strength': '1190',
                      'Braider Rejects': '1332',
                      'Broken Pullwire': '1332',
                      'Broken Wire': '1047',
                      'Bubbles': '1048',
                      'Bunched Braid': '1406',
                      'Burn': '1406',
                      'Burned Heal': '1288',
                      'Burrs': '1289',
                      'Count Discrepancy': '1116',
                      'Count Error Over': '1422',
                      'Count Error Under': '1090',
                      'Cracks': '1013',
                      'DIM 06 Outer Diameter Under Sized': '1288',
                      'DIM 07 Outer Diameter Under Sized': '1289',
                      'DIM 9 Outer Diameter UnderSized': '1288',
                      'DIM01 OS': 'D01O',
                      'DIM01 US': 'D01U',
                      'DIM03 US': 'D03U',
                      'DIM05 OS': 'D05O',
                      'DIM05 US': 'D05U',
                      'DIM06 OS': 'D06O',
                      'DIM06 US': 'D06U',
                      'DIM07 Length UnderSized ': '1336',
                      'DIM07 OS': 'D07O',
                      'DIM09 OS': 'D09O',
                      'DIM09 US': 'D09U',
                      'DIM13 OS': 'D13O',
                      'Damage': '1422',
                      'Damage Tip': '1155',
                      'Damage proximal by cutting': '1061',
                      'Damage skive by cutting': '1452',
                      'Damaged Braid': '1462',
                      'Damaged Cut on Tip': '1467',
                      'Damaged Hypotube': '1114',
                      'Damaged Inner Surface': '1128',
                      'Damaged Liner': '1116',
                      'Damaged PTFE': '1118',
                      'Damaged Shaft': '1120',
                      'Damaged Surface': '1128',
                      'Damaged Tip': '1125',
                      'Damaged Unit': '1127',
                      'Damaged Wire': '1047',
                      'Damaged shaft': '1120',
                      'Damaged tip': '1169',
                      'Deep Weld': '1101',
                      'Deep scratches': '1128',
                      'Deformed': '1531',
                      'Deformed Tip': '1495',
                      'Delamination': '1047',
                      'Dents': '1134',
                      'Dents on Tube / Dented Tube': '1348',
                      'Dim 03 Length Oversized': '1125',
                      'Dim 03 Length Undersized': '1047',
                      'Dim 04 Length Oversized': '1132',
                      'Dim 04 Length Undersized': '1336',
                      'Dim 05 Length Oversized': '1336',
                      'Dim 05 undersized': '1336',
                      'Dim 06 Outer Diameter Oversized': '1336',
                      'Dim 1 Outer Diameter Oversized': '1128',
                      'Dim 1 Outer Diameter Undersized': '1336',
                      'Dim 2 Inner Diameter Oversized': '1120',
                      'Dim 2 Inner Diameter Undersized': '1336',
                      'Dim 5 Length Oversized': '1288',
                      'Dim 5 Length Undersized': '1289',
                      'Dim 6 Outer Diameter Oversized': '1336',
                      'Dim 6 Outer Diameter Undersized': '1336',
                      'Dim 7 Length Oversized': '1288',
                      'Dim 7 Length Undersized': '1289',
                      'Dim 9 Outer Diameter Oversized': '1336',
                      'Dim 9 Outer Diameter Undersized': '1336',
                      'Dimensions out of Spec': '1013',
                      'Discoloration': '1336',
                      'Discolouration': '1336',
                      'Distortion': '1534',
                      'Dropped Unit': '1534',
                      'Dropped Unit (no rework allowed)': '1177',
                      'E001 hypotube showing': '1013',
                      'EDM Holes': '1029',
                      'Engineering Scrap': '1029',
                      'Exit Gate Off': '1509',
                      'Exposed Braid': '1509',
                      'Exposed Hypotube': '1155',
                      'Exposed Pull Ring': '1510',
                      'Exposed Wire': '1193',
                      'FM on Shaft': '1185',
                      'Failed Leak Test': '1287',
                      'Fibers': '1174',
                      'Flash': '1177',
                      'Foreign Material': '1190',
                      'Foreign Material (no rework allow)': '1538',
                      'Foreign material': '1391',
                      'Gap': '1193',
                      'Gate Flash': '1197',
                      'Glue Damage': '1116',
                      'Heat Off Stopper': '1126',
                      'Hypotube out of position': '1190',
                      'ID Blocked': '1538',
                      'Incorrect Tempeature': '1391',
                      'Inner Diameter Block': '1538',
                      'Inner Diameter Blow Out': '1289',
                      'Kinked': '1253',
                      'Kinked Pullwire': '1256',
                      'Kinked shaft': '1257',
                      'Leak FAIL': '1287',
                      'Leak Test': '1556',
                      'Length Short': '1289',
                      'Length too Long': '1288',
                      'Length too short': '1289',
                      'Loose Particulate Matter': '1531',
                      'Lump/Bump': '1306',
                      'Lumps': '1307',
                      'Mandrel Remover Reject': '1310',
                      'Material Overflow': '1531',
                      'Micropores': '1456',
                      'Misaligned': '1556',
                      'Misassemble': '1556',
                      'Misassembled': '1556',
                      'Misassembled Extrusions': '1556',
                      'Missassembled': '1556',
                      'No Bond': '1325',
                      'OD Fail': '1336',
                      'OD out of spec': '1337',
                      'OD/ID out of spec': '1338',
                      'Other defect not listed': '1343',
                      'Over Flow': '1347',
                      'Overalign': '1556',
                      'Overall Length Long': '1288',
                      'Overall Length Short': '1289',
                      'Overflow': '1531',
                      'Overmelt': '1347',
                      'PTFE on Pull Wire': '1118',
                      'Pad Print Defects': '1350',
                      'Paint Marks': '1354',
                      'Pancake': '1116',
                      'Protrusion': '1060',
                      'Raised Material': '1190',
                      'Re-glue': '1332',
                      'Reglue': '1332',
                      'Ridge': '1561',
                      'Samples': '1400',
                      'Scratch': '1406',
                      'Scratches': '1406',
                      'Segment Length Long': '1288',
                      'Segment Length Short': '1289',
                      'Short Wire': '1116',
                      'Skive Damage': '1422',
                      'Skive Mark': '1422',
                      'Skive Mark ': '1422',
                      'Stain': '1190',
                      'Stains/Discolouration': '1441',
                      'Stringers': '1452',
                      'Stringing': '1452',
                      'Surface Damage': '1455',
                      'Surface Pits / Voids': '1456',
                      'Swaging Defects': '1457',
                      'Tails': '1462',
                      'Tensile Test': '1467',
                      'Thin Wall': '1470',
                      'Tight Liner': '1118',
                      'Tight Mandrel': '1472',
                      'Tip Assembly': '1473',
                      'Tip Damage': '1474',
                      'Tip Damaged': '1101',
                      'Tip damage': '1474',
                      'Tubes different lenghts': '1486',
                      'Twisted Tip': '1488',
                      'Voids': '1495',
                      'Wall Thickness': '1564',
                      'White Line': '1116',
                      'White Spot Over Stretch': '1348',
                      'Window Close (SL/US)': '1013',
                      'Window Miscut': '1013',
                      'Window Open (SL/OS)': '1013',
                      'Wire Bent': '1029',
                      'Wire Bent ': '1029',
                      'Wire Out': '1509',
                      'Wire out of position': '1509',
                      'Wrinkles': '1510'
                      }
'''
Work Center: column 2
Operation: column 1
Scrap Code: correspond with Scrap Description
Scrap Description: column 4, need to expand the short form 
Op. Good Qty: column 3
Op. Scrap Qty: minus by Op. Good Qty
'''
